# Generated by Django 4.0.6 on 2022-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آگهی')),
                ('idcode', models.CharField(max_length=12, verbose_name='کد ورقه مصرفی')),
                ('company', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ ورقه')),
                ('width', models.FloatField(verbose_name='عرض ورقه')),
                ('height', models.FloatField(verbose_name='طول ورقه')),
                ('woodType', models.CharField(choices=[('HG', 'های گلس'), ('MF', 'ام دی اف'), ('LT', 'لترون')], max_length=2, verbose_name='نوع ورقه')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='VcardPhoto/', verbose_name='تصویر شاخص')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
            ],
            options={
                'verbose_name': 'تبلیغات ورقه',
                'verbose_name_plural': 'تبلیغات ورقه',
            },
        ),
    ]
